### ISSUE TITLE
Wrong indentation after single-line where and do

### ISSUE THREAD

**Issue by Caagr98** [itchyny/vim-haskell-indent#18] opened 2020-05-21 16:14 UTC
I realize this might not be good code style, but putting `where` or `do` blocks and their contents on a single line often makes the next line incorrectly indented.
```
instance Show A where show A = "A"
                      instance Show B where show B = "B"
```
```
run (Add a) = do modify (+a); get
                 run (Multiply a) = do modify (*a); get
```

Differentiating those cases from those where you do want the next line to be indented might be difficult though.

**Comment by itchyny** [comment] 2020-05-22 01:03
These cases are too hard to deal with in this plugin. This plugin is just an editing helper, not a perfect reformatter. There's no action to take for this issue so closing.

**Closed by itchyny** 2020-05-22 01:03 UTC

**Comment by itchyny** [comment] 2020-05-22 02:45
I noticed that I can't reproduce these cases.
![h](https://user-images.githubusercontent.com/375258/82626006-9ec84400-9c21-11ea-830e-f5ed951042af.gif)
